//
//  Data.swift
//  AwardSeason1YuriiSameliuk
//
//  Created by Yurii Sameliuk on 30/09/2021.
//

import Foundation

    let dataModel = [
        Model(id: 1,
              avatar: "mode2",
              image: "model3",
              title: "HOTTEST BIKINI",
              date: "22.01.2020",
              name: "Designer Fashion",
              like: "1890",
              duration: 0,
              description: "Boldest Bikini, Swimwear, and Bathing Suits Compilatio.! Runway Models in the most beautiful bathing suits of the latest Miami Fashion Week shows. This is a selection of designer swimwear curated from many shows. You'll be able to spot with your clever eye changes in trends from 2019 to 2020 collections. Enjoy the show!",
              video: nil),
        Model(id: 2,
              avatar: "mode2",
              image: "model4",
              title: "HOTTEST BIKINI",
              date: "22.01.2020",
              name: "Designer Fashion",
              like: "5409",
              duration: 0,
              description: "Boldest Bikini, Swimwear, and Bathing Suits Compilatio.! Runway Models in the most beautiful bathing suits of the latest Miami Fashion Week shows. This is a selection of designer swimwear curated from many shows. You'll be able to spot with your clever eye changes in trends from 2019 to 2020 collections. Enjoy the show!",
              video: nil),
        Model(id: 3,
              avatar: "mode2",
              image: "model6",
              title: "HOTTEST BIKINI",
              date: "22.01.2020",
              name: "Designer Fashion",
              like: "8340",
              duration: 0,
              description: "Boldest Bikini, Swimwear, and Bathing Suits Compilatio.! Runway Models in the most beautiful bathing suits of the latest Miami Fashion Week shows. This is a selection of designer swimwear curated from many shows. You'll be able to spot with your clever eye changes in trends from 2019 to 2020 collections. Enjoy the show!",
              video: nil),
        Model(id: 4,
              avatar: "mode2",
              image: "model7",
              title: "HOTTEST BIKINI",
              date: "22.01.2020",
              name: "Designer Fashion",
              like: "2290",
              duration: 0,
              description: "Boldest Bikini, Swimwear, and Bathing Suits Compilatio.! Runway Models in the most beautiful bathing suits of the latest Miami Fashion Week shows. This is a selection of designer swimwear curated from many shows. You'll be able to spot with your clever eye changes in trends from 2019 to 2020 collections. Enjoy the show!",
              video: nil),
        Model(id: 5,
              avatar: "mode2",
              image: "model8",
              title: "HOTTEST BIKINI",
              date: "22.01.2020",
              name: "Designer Fashion",
              like: "6850",
              duration: 0,
              description: "Boldest Bikini, Swimwear, and Bathing Suits Compilatio.! Runway Models in the most beautiful bathing suits of the latest Miami Fashion Week shows. This is a selection of designer swimwear curated from many shows. You'll be able to spot with your clever eye changes in trends from 2019 to 2020 collections. Enjoy the show!",
              video: nil),
        Model(id: 6,
              avatar: "car1",
              image: "car4",
              title: "The Best of WRC Rally",
              date: "23.12.2020",
              name: "Rally racing",
              like: "9340",
              duration: 0,
              description: "This is the best of WRC Rally 2020. These are the best crashes, action, and maximum attack moments from the year!",
              video: nil),
        Model(id: 7,
              avatar: "car1",
              image: "car5",
              title: "The Best of WRC Rally",
              date: "23.12.2020",
              name: "Rally racing",
              like: "5380",
              duration: 0,
              description: "This is the best of WRC Rally 2020. These are the best crashes, action, and maximum attack moments from the year!",
              video: nil),
        Model(id: 8,
              avatar: "car1",
              image: "car6",
              title: "The Best of WRC Rally",
              date: "23.12.2020",
              name: "Rally racing",
              like: "2330",
              duration: 0,
              description: "This is the best of WRC Rally 2020. These are the best crashes, action, and maximum attack moments from the year!",
              video: nil),
        Model(id: 9,
              avatar: "car1",
              image: "car8",
              title: "The Best of WRC Rally",
              date: "23.12.2020",
              name: "Rally racing",
              like: "5677",
              duration: 0,
              description: "This is the best of WRC Rally 2020. These are the best crashes, action, and maximum attack moments from the year!",
              video: nil),
        Model(id: 10,
              avatar: "car1",
              image: "car10",
              title: "The Best of WRC Rally",
              date: "23.12.2020",
              name: "Rally racing",
              like: "9340",
              duration: 0,
              description: "This is the best of WRC Rally 2020. These are the best crashes, action, and maximum attack moments from the year!",
              video: nil),
        Model(id: 11,
              avatar: "car1",
              image: nil,
              title: "The Best of WRC Rally",
              date: "23.12.2020",
              name: "Rally racing",
              like: "9340",
              duration: 12,
              description: "This is the best of WRC Rally 2020. These are the best crashes, action, and maximum attack moments from the year!",
              video: Bundle.main.url(forResource: "carVideo1", withExtension: "mp4")),
        Model(id: 12,
              avatar: "car1",
              image: nil,
              title: "The Best of WRC Rally",
              date: "23.12.2020",
              name: "Rally racing",
              like: "5430",
              duration: 12,
              description: "This is the best of WRC Rally 2020. These are the best crashes, action, and maximum attack moments from the year!",
              video: Bundle.main.url(forResource: "carVideo2", withExtension: "mp4")),
        Model(id: 13,
              avatar: "car1",
              image: nil,
              title: "The Best of WRC Rally",
              date: "23.12.2020",
              name: "Rally racing",
              like: "5368",
              duration: 5,
              description: "This is the best of WRC Rally 2020. These are the best crashes, action, and maximum attack moments from the year!",
              video: Bundle.main.url(forResource: "carVideoCrash1", withExtension: "mp4")),
        Model(id: 14,
              avatar: "car1",
              image: nil,
              title: "The Best of WRC Rally",
              date: "23.12.2020",
              name: "Rally racing",
              like: "5430",
              duration: 86,
              description: "This is the best of WRC Rally 2020. These are the best crashes, action, and maximum attack moments from the year!",
              video: Bundle.main.url(forResource: "carVideoJump1", withExtension: "mp4")),
        Model(id: 15,
              avatar: "mode2",
              image: nil,
              title: "HOTTEST BIKINI",
              date: "22.01.2020",
              name: "Designer Fashion",
              like: "6850",
              duration: 15,
              description: "Boldest Bikini, Swimwear, and Bathing Suits Compilatio.! Runway Models in the most beautiful bathing suits of the latest Miami Fashion Week shows. This is a selection of designer swimwear curated from many shows. You'll be able to spot with your clever eye changes in trends from 2019 to 2020 collections. Enjoy the show!",
              video: Bundle.main.url(forResource: "modelVideo1", withExtension: "mp4")),
        Model(id: 16,
              avatar: "mode2",
              image: nil,
              title: "HOTTEST BIKINI",
              date: "22.01.2020",
              name: "Designer Fashion",
              like: "7450",
              duration: 49,
              description: "Boldest Bikini, Swimwear, and Bathing Suits Compilatio.! Runway Models in the most beautiful bathing suits of the latest Miami Fashion Week shows. This is a selection of designer swimwear curated from many shows. You'll be able to spot with your clever eye changes in trends from 2019 to 2020 collections. Enjoy the show!",
              video: Bundle.main.url(forResource: "modelVideo2", withExtension: "mp4")),
        Model(id: 17,
              avatar: "mode2",
              image: nil,
              title: "HOTTEST BIKINI",
              date: "22.01.2020",
              name: "Designer Fashion",
              like: "1850",
              duration: 15,
              description: "Boldest Bikini, Swimwear, and Bathing Suits Compilatio.! Runway Models in the most beautiful bathing suits of the latest Miami Fashion Week shows. This is a selection of designer swimwear curated from many shows. You'll be able to spot with your clever eye changes in trends from 2019 to 2020 collections. Enjoy the show!",
              video: Bundle.main.url(forResource: "modelVideo3", withExtension: "mp4")),
        Model(id: 18,
              avatar: "mode2",
              image: nil,
              title: "HOTTEST BIKINI",
              date: "22.01.2020",
              name: "Designer Fashion",
              like: "1230",
              duration: 9,
              description: "Boldest Bikini, Swimwear, and Bathing Suits Compilatio.! Runway Models in the most beautiful bathing suits of the latest Miami Fashion Week shows. This is a selection of designer swimwear curated from many shows. You'll be able to spot with your clever eye changes in trends from 2019 to 2020 collections. Enjoy the show!",
              video: Bundle.main.url(forResource: "modelVideo4", withExtension: "mp4")),
        Model(id: 19,
              avatar: "car1",
              image: nil,
              title: "The Best of WRC Rally",
              date: "23.12.2020",
              name: "Rally racing",
              like: "9999",
              duration: 49,
              description: "This is the best of WRC Rally 2020. These are the best crashes, action, and maximum attack moments from the year!",
              video: Bundle.main.url(forResource: "CarDemoTest", withExtension: "mp4")),
    ]
